server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: restaurant-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/restaurant_db?TimeZone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    admin:
      auto-create: true
    consumer:
      group-id: restaurant-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          orderCreatedEvent:org.example.restaurant_domain.restaurant_domain_core.event.OrderCreatedEvent,
          paymentCompletedEvent:org.example.restaurant_domain.restaurant_domain_core.event.PaymentCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 1
      enable.idempotence: true
      max-in-flight-requests-per-connection: 5
      properties:
        spring.json.type.mapping: >
          restaurantApprovedEvent:org.example.restaurant_domain.restaurant_domain_core.event.RestaurantApprovedEvent,
          restaurantRejectedEvent:org.example.restaurant_domain.restaurant_domain_core.event.RestaurantRejectedEvent

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: restaurant-service

kafka:
  topics:
    payment-completed: payment.completed

logging:
  level:
    root: INFO
    org.example: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
